// Copyright 2026 ETH Zurich and University of Bologna.
// SPDX-License-Identifier: Apache-2.0
//
// Build-time MSHR bank-hash selection. Runs on the HOST and emits the constants
// the target writes straight into its CSRs, so no core searches for them at boot.
//
// It includes the same runtime/gemm_hash.h the target would have used, so the
// scoring cannot drift from the model it is supposed to reproduce.
//
// Addresses: the score reads address bits [shift+2, shift+6). Every operand is
// aligned to QWEN_MESH_SWEEP, so with the shift capped at QWEN_HASH_SHIFT_MAX
// those bits come entirely from the offset within the buffer and not at all from
// the buffer's link address -- which is why passing offsets here is exact rather
// than an approximation. The target asserts that alignment at boot.
#include <stdint.h>
#include <stdio.h>

#include "qwen_layout.h"
#include "gemm_config.h"
#include "gemm_burst.h"
#include "gemm_hash.h"

#define QWEN_HASH_SHIFT_MAX 8

int main(void) {
  const uint32_t banks = (MSHR_CFG_ENTRIES) / (MSHR_CFG_WAYS);

  printf("// GENERATED by script/gen_hash.c -- do not hand-edit.\n");
  printf("// Bank-hash selectors for this shape, one triple per group.\n");
  printf("#ifndef QWEN_HASH_H\n#define QWEN_HASH_H\n\n");
  printf("#define QWEN_HASH_SHIFT_MAX %u\n", (unsigned)QWEN_HASH_SHIFT_MAX);
  printf("#define QWEN_HASH_BANKS %u\n\n", (unsigned)banks);
  printf("// { bank_shift_single, bank_shift_burst, bank_burst_bits }\n");
  printf("static const uint8_t qwen_hash_sel[%u][3] = {\n", (unsigned)NUM_GROUPS);

  for (uint32_t g = 0; g < (uint32_t)NUM_GROUPS; ++g) {
    // X's replica for this group; W always starts a buffer, so offset zero.
    const uint32_t a = QWEN_X_REPLICA_OF(g) * (uint32_t)QWEN_X_STRIDE_B;
    uint32_t single = 4, burst = 4, bits = 0;
    gemm_hash_score_t best_s = gemm_hash_evaluate(a, 0, g, banks, 0, single, 0);
    gemm_hash_score_t best_b = gemm_hash_evaluate(a, 0, g, banks, 1, burst, bits);
    for (uint32_t shift = 4; shift <= QWEN_HASH_SHIFT_MAX; ++shift) {
      gemm_hash_score_t s = gemm_hash_evaluate(a, 0, g, banks, 0, shift, 0);
      if (gemm_hash_better(s, shift, 0, best_s, single, 0)) { best_s = s; single = shift; }
      for (uint32_t bb = 0; bb <= 1; ++bb) {
        if (shift < GEMM_BURST_HASH_ALIGN + bb) continue;
        s = gemm_hash_evaluate(a, 0, g, banks, 1, shift, bb);
        if (gemm_hash_better(s, shift, bb, best_b, burst, bits)) {
          best_b = s; burst = shift; bits = bb;
        }
      }
    }
    printf("  {%u, %u, %u},  // group %2u: spread single %u, burst %u\n",
           (unsigned)single, (unsigned)burst, (unsigned)bits, (unsigned)g,
           (unsigned)best_s.spread, (unsigned)best_b.spread);
  }
  printf("};\n\n#endif\n");
  return 0;
}
