// Copyright 2026 ETH Zurich and University of Bologna.
// SPDX-License-Identifier: Apache-2.0
//
// Build-time MSHR bank-hash selection. Runs on the HOST and emits the constants
// the target writes straight into its CSRs, so no core searches for them at boot.
//
// It includes the same runtime/gemm_hash.h the target would have used, so the
// scoring cannot drift from the model it is supposed to reproduce.
//
// Addresses: the score reads address bits [shift+2, shift+6). Every operand is
// aligned to QWEN_MESH_SWEEP, so with the shift capped at QWEN_HASH_SHIFT_MAX
// those bits come entirely from the offset within the buffer and not at all from
// the buffer's link address -- which is why passing offsets here is exact rather
// than an approximation. The target asserts that alignment at boot.
#include <stdint.h>
#include <stdio.h>

#include "qwen_layout.h"
#include "gemm_config.h"
#include "gemm_burst.h"
#include "gemm_hash.h"

#define QWEN_HASH_SHIFT_MAX 8
// What one core actually has outstanding, derived rather than assumed.
//
// A vector load is split into 16-word bursts (gemm_burst_next), 64 bytes apart.
// Each full burst costs MaxBurstWords/lanes ids in EVERY reorder buffer, and a
// ROB holds GEMM_BURST_ROB_DEPTH, so the ids a load needs decide how many loads
// can be in flight -- often just one. Both axes matter and they pull opposite
// ways: sub-requests step by 16 words, reduction steps by a whole row.
#define QWEN_VL_HW ((VLEN) * GEMM_LMUL(KERNEL_SIZE) / (8u * GEMM_ELEM_BYTES))
#define QWEN_VL_CAP \
  ((GEMM_BURST_ROB_DEPTH) * (GEMM_BURST_LANES) * 4u / GEMM_ELEM_BYTES)
#define QWEN_VL_MAX ((QWEN_VL_HW) < (QWEN_VL_CAP) ? (QWEN_VL_HW) : (QWEN_VL_CAP))
#define QWEN_BURST_WORDS (GEMM_BURST_TILE_WORDS)
#define QWEN_IDS_PER_BURST ((QWEN_BURST_WORDS) / (GEMM_BURST_LANES))

int main(void) {
  const uint32_t banks = (MSHR_CFG_ENTRIES) / (MSHR_CFG_WAYS);

  // What one group actually has outstanding, which is what the banks have to
  // hold: the distinct column blocks it owns -- cores sharing a block merge into
  // one entry -- times the bursts each load splits into, across the loads that
  // fit in the reorder buffer at once.
  //
  // The shared model in gemm_hash.h scores only the spread ACROSS CORES at a
  // single step. That misses both axes that matter here: the sub-requests of one
  // load, 64 bytes apart, and the reduction step, a whole row apart.
  // Cores sharing one column block -- main.c's share_burst. It is B/KERNEL_SIZE,
  // NOT B: with KS > 1 a core owns KS rows, so B/KS row chunks share a block and
  // the group holds GEMM_CPG/(B/KS) DISTINCT blocks. Using B here collapsed
  // `blocks` to 1 at B == GEMM_CPG, which made every shift tie at one bank and
  // let the in-flight tie-break pick the widest (worst) granule.
  const uint32_t rows   = (uint32_t)QWEN_B / (uint32_t)KERNEL_SIZE;
  const uint32_t share  = (rows < GEMM_CPG) ? (rows ? rows : 1u) : (uint32_t)GEMM_CPG;
  const uint32_t blocks = (uint32_t)GEMM_CPG / share;
  const uint32_t span   = (uint32_t)QWEN_LDP / (uint32_t)GEMM_PBLOCKS(KERNEL_SIZE);
  // One load covers min(span, VL_MAX) elements and splits into that many bursts;
  // its id cost then caps how many loads can overlap.
  // Below 16-byte spans the kernel keeps the stripe cap, so a load is one burst.
  const uint32_t cap    = (QWEN_SPAN_ALIGN >= 8) ? (uint32_t)QWEN_VL_MAX
                                                 : (uint32_t)QWEN_STRIPE_E;
  const uint32_t vl     = (span < cap) ? span : cap;
  const uint32_t subs   = (vl * GEMM_ELEM_BYTES + QWEN_BURST_WORDS * 4u - 1u) /
                          (QWEN_BURST_WORDS * 4u);
  const uint32_t ids    = subs * QWEN_IDS_PER_BURST;
  const uint32_t inflight = ids && (uint32_t)GEMM_BURST_ROB_DEPTH / ids ?
                            (uint32_t)GEMM_BURST_ROB_DEPTH / ids : 1u;

  printf("// GENERATED by script/gen_hash.c -- do not hand-edit.\n");
  printf("// Bank-hash selectors for this shape, one triple per group.\n");
  printf("#ifndef QWEN_HASH_H\n#define QWEN_HASH_H\n\n");
  printf("#define QWEN_HASH_SHIFT_MAX %u\n", (unsigned)QWEN_HASH_SHIFT_MAX);
  printf("#define QWEN_HASH_BANKS %u\n\n", (unsigned)banks);
  printf("// { bank_shift_single, bank_shift_burst, bank_burst_bits }\n");
  printf("// one load = %u elems = %u bursts = %u ids/ROB -> %u load(s) in flight\n",
         (unsigned)vl, (unsigned)subs, (unsigned)ids, (unsigned)inflight);
  // The sharing model the scores are built on, and the ceiling they can reach:
  // a group cannot occupy more banks than it has distinct addresses outstanding.
  printf("// ks=%u share=%u blocks=%u -> %u distinct addrs/step, bank ceiling %u\n",
         (unsigned)KERNEL_SIZE, (unsigned)share, (unsigned)blocks,
         (unsigned)(blocks * subs),
         (unsigned)(blocks * subs < banks ? blocks * subs : banks));
  printf("static const uint8_t qwen_hash_sel[%u][3] = {\n", (unsigned)NUM_GROUPS);

  for (uint32_t g = 0; g < (uint32_t)NUM_GROUPS; ++g) {
    const uint32_t a = QWEN_X_REPLICA_OF(g) * (uint32_t)QWEN_X_STRIDE_B;
    uint32_t single = 4, burst = 4, bits = 0;
    gemm_hash_score_t best_s = gemm_hash_evaluate(a, 0, g, banks, 0, single, 0);
    uint32_t best_now = 0, best_soon = 0;

    for (uint32_t shift = 4; shift <= QWEN_HASH_SHIFT_MAX; ++shift) {
      gemm_hash_score_t s = gemm_hash_evaluate(a, 0, g, banks, 0, shift, 0);
      if (gemm_hash_better(s, shift, 0, best_s, single, 0)) { best_s = s; single = shift; }

      for (uint32_t bb = 0; bb <= 1; ++bb) {
        if (shift < GEMM_BURST_HASH_ALIGN + bb) continue;
        uint32_t now = 0, soon = 0;
        for (uint32_t loads = 1; loads <= inflight; ++loads) {
          uint32_t seen = 0;
          for (uint32_t ld = 0; ld < loads; ++ld)          // successive k
            for (uint32_t blk = 0; blk < blocks; ++blk)    // the group's blocks
              for (uint32_t sub = 0; sub < subs; ++sub) {  // bursts of one load
                // Consecutive p_blocks of a group are `span` elements apart
                // (main.c: p_start = p_block * p_span, p_block = cid / rows), so
                // the stride is span, not span*share.
                const uint32_t word =
                    (ld * (uint32_t)QWEN_LDP + blk * span) * GEMM_ELEM_BYTES / 4 +
                    sub * QWEN_BURST_WORDS;
                seen |= 1u << gemm_hash_bank(word, shift, bb, banks);
              }
          uint32_t count = 0;
          for (uint32_t b = 0; b < banks; ++b) count += (seen >> b) & 1u;
          if (loads == 1) now = count; else soon = count;
        }
        if (soon < now) soon = now;
        if (now > best_now || (now == best_now && soon > best_soon)) {
          best_now = now; best_soon = soon; burst = shift; bits = bb;
        }
      }
    }
    printf("  {%u, %u, %u},  // group %2u: burst banks %u now, %u with %u in flight\n",
           (unsigned)single, (unsigned)burst, (unsigned)bits, (unsigned)g,
           (unsigned)best_now, (unsigned)best_soon, (unsigned)inflight);
  }
  printf("};\n\n#endif\n");
  return 0;
}
