// Copyright 2026 ETH Zurich and University of Bologna.
// SPDX-License-Identifier: Apache-2.0
//
// Build-time choice of the K tile height (QWEN_KT) and the output strip width
// (QWEN_PT). Runs on the HOST and writes data/qwen_tiles.h. The rule and the reasons
// are in qwen_layout.h ("K tile height and strip width"); this file only searches.
//
// It evaluates the same QWEN_PT_OK_K legality test the target's _Static_asserts use,
// so a width chosen here can never be one the build then rejects.
#include <stdint.h>
#include <stdio.h>

#define QWEN_TILE_PROBE 1  // qwen_layout.h: do not include the header this writes
#include "qwen_layout.h"

#ifndef QWEN_KT_MAX
#define QWEN_KT_MAX 640
#endif

// The widest legal strip beside K tiles of kt rows (fewest strips); 0 if none fits.
static uint32_t widest(uint32_t kt) {
  for (uint32_t d = 1; d <= 64; d *= 2) {
    const uint32_t pt = (uint32_t)QWEN_LDP / d;
    if (((uint32_t)QWEN_LDP % d) == 0 && QWEN_PT_OK_K(kt, pt)) return pt;
  }
  return 0;
}

// The strip width that goes with kt: the pinned one if it is legal there, else the widest.
static uint32_t fit(uint32_t kt) {
#if defined(QWEN_PT_REQ) && (QWEN_PT_REQ) > 0
  return QWEN_PT_OK_K(kt, (uint32_t)QWEN_PT_REQ) ? (uint32_t)QWEN_PT_REQ : 0u;
#else
  return widest(kt);
#endif
}

int main(void) {
  uint32_t kt = 0, pt = 0;
#if defined(QWEN_KT_REQ) && (QWEN_KT_REQ) > 0
  kt = (uint32_t)QWEN_KT_REQ;
  pt = fit(kt);
  const char *how = "pinned (qwen_kt)";
#else
  // Tallest first: K/2, K/4, ... -- an even tile count, an even KT (the kernel's n loop
  // unrolls by 2), at most QWEN_KT_MAX, and a legal strip width beside it.
  for (uint32_t s = 2; s <= 128 && !kt; s *= 2) {
    const uint32_t k = (uint32_t)QWEN_K / s;
    if (((uint32_t)QWEN_K % s) || (k % 2u) || k > (uint32_t)QWEN_KT_MAX) continue;
    if ((pt = fit(k)) != 0) kt = k;
  }
  const char *how = "auto (tallest even tile count <= QWEN_KT_MAX with a legal strip)";
#endif
  if (!kt || !pt) {
    fprintf(stderr,
            "gen_tiles: no legal K tile / strip for B=%u K=%u P=%u (kt=%u pt=%u, L1 %u B): "
            "lower qwen_kt / the batch, or raise qwen_kt_max\n",
            (unsigned)QWEN_B, (unsigned)QWEN_K, (unsigned)QWEN_P, (unsigned)kt, (unsigned)pt,
            (unsigned)QWEN_L1_BYTES);
    return 1;
  }
  printf("// GENERATED by script/gen_tiles.c -- do not hand-edit.\n");
  printf("#ifndef QWEN_TILES_H\n#define QWEN_TILES_H\n");
#if defined(QWEN_PT_REQ) && (QWEN_PT_REQ) > 0
  const char *pt_how = "pinned (qwen_pt)";
#else
  const char *pt_how = "widest legal beside KT";
#endif
  printf("// KT %s; PT %s.\n", how, pt_how);
  printf("// %u K tiles x %u strips; W buffer 2 x %u x %u; L1 %.1f of %.1f MiB\n",
         (unsigned)(QWEN_K / kt), (unsigned)(QWEN_LDP / pt), (unsigned)kt, (unsigned)pt,
         QWEN_L1_KP(kt, pt) / 1048576.0, QWEN_L1_BYTES / 1048576.0);
  printf("#define QWEN_KT %u\n#define QWEN_PT %u\n#endif\n", (unsigned)kt, (unsigned)pt);
  return 0;
}
