// Copyright 2026 ETH Zurich and University of Bologna.
// SPDX-License-Identifier: Apache-2.0
//
// Writes the operand images the ELF carries, plus the assembly stub that places
// them in L2. Runs on the HOST: the target then starts with W and X already in
// memory and fills nothing.
//
// The values come from qwen_pattern.h, the same header the target verifies
// against, so a preloaded operand and its expectation cannot disagree.
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include "qwen_layout.h"
#include "qwen_pattern.h"

static void write_bin(const char *path, uint32_t rows, uint32_t cols,
                      uint16_t (*value)(uint32_t, uint32_t, uint32_t),
                      uint32_t stages) {
  FILE *f = fopen(path, "wb");
  if (!f) { perror(path); exit(1); }
  // One row at a time: the full image is far too large to hold in memory.
  uint16_t *row = malloc((size_t)cols * sizeof(uint16_t));
  if (!row) { fprintf(stderr, "out of memory\n"); exit(1); }
  for (uint32_t s = 0; s < stages; ++s)
    for (uint32_t r = 0; r < rows; ++r) {
      for (uint32_t c = 0; c < cols; ++c) row[c] = value(s, r, c);
      if (fwrite(row, sizeof(uint16_t), cols, f) != cols) { perror(path); exit(1); }
    }
  free(row);
  fclose(f);
}

// W is [stage][K][LDP]; columns past P are alignment padding the kernel never
// reads, and are zero so a run that does read them is obviously wrong.
static uint16_t w_value(uint32_t stage, uint32_t k, uint32_t p) {
  return (p < (uint32_t)QWEN_P) ? qwen_w_bits(stage, k, p) : 0u;
}
static uint16_t x_value(uint32_t stage, uint32_t b, uint32_t k) {
  (void)stage;
  return qwen_x_bits(b, k);
}

int main(int argc, char **argv) {
  if (argc != 2) { fprintf(stderr, "usage: %s <data-dir>\n", argv[0]); return 2; }
  char path[4096];

  snprintf(path, sizeof(path), "%s/qwen_w.bin", argv[1]);
  write_bin(path, QWEN_K, QWEN_LDP, w_value, QWEN_STAGES_N);

  snprintf(path, sizeof(path), "%s/qwen_x.bin", argv[1]);
  write_bin(path, QWEN_B, QWEN_K, x_value, 1);

  // The stub: .incbin costs the assembler a copy, where an initialised C array
  // of this many elements would never finish compiling.
  snprintf(path, sizeof(path), "%s/qwen_operands.S", argv[1]);
  FILE *f = fopen(path, "w");
  if (!f) { perror(path); return 1; }
  fprintf(f,
          "// GENERATED by script/gen_operands.c -- do not hand-edit.\n"
          "  .section .l2, \"a\", @progbits\n"
          "  .balign %u\n"
          "  .globl qwen_w_l2\n"
          "qwen_w_l2:\n"
          "  .incbin \"%s/qwen_w.bin\"\n"
          "  .balign %u\n"
          "  .globl qwen_x_l2\n"
          "qwen_x_l2:\n"
          "  .incbin \"%s/qwen_x.bin\"\n",
          (unsigned)QWEN_MESH_SWEEP, argv[1], (unsigned)QWEN_MESH_SWEEP, argv[1]);
  fclose(f);
  return 0;
}
