# Copyright 2025 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: terapool
description: "Terapool AXI NoC"
network_type: "narrow-wide"

routing:
  route_algo: "SRC"
  use_id_table: true

protocols:
  - name: "narrow_in"
    type: "narrow"
    protocol: "AXI4"
    data_width: 64
    addr_width: 32
    id_width: 1
    user_width: 1
    direction: "input"
  - name: "narrow_out"
    type: "narrow"
    protocol: "AXI4"
    data_width: 64
    addr_width: 32
    id_width: 1
    user_width: 1
    direction: "output"
  - name: "wide_in"
    type: "wide"
    protocol: "AXI4"
    data_width: 512
    addr_width: 32
    id_width: 2
    user_width: 1
  - name: "wide_out"
    type: "wide"
    protocol: "AXI4"
    data_width: 512
    addr_width: 32
    id_width: 2
    user_width: 1

endpoints:
  - name: "group"
    array: [4, 4]
    mgr_port_protocol:
      - "wide_in"
  - name: "hbm0"
    addr_range:
      - start: 0x8000_0000
        end: 0x800F_FFFF
    sbr_port_protocol:
      - "wide_out"
  - name: "hbm1"
    addr_range:
      - start: 0x8010_0000
        end: 0x801F_FFFF
    sbr_port_protocol:
      - "wide_out"
  - name: "hbm2"
    addr_range:
      - start: 0x8020_0000
        end: 0x802F_FFFF
    sbr_port_protocol:
      - "wide_out"
  - name: "hbm3"
    addr_range:
      - start: 0x8030_0000
        end: 0x803F_FFFF
    sbr_port_protocol:
      - "wide_out"
  - name: "hbm4"
    addr_range:
      - start: 0x8040_0000
        end: 0x804F_FFFF
    sbr_port_protocol:
      - "wide_out"
  - name: "host_hbm5_peri"
    addr_range:
      - start: 0x8050_0000
        end: 0x805F_FFFF
      - start: 0x0000_0000
        end: 0x7FFF_FFFF
      - start: 0xA000_0000
        end: 0xC000_FFFF
    mgr_port_protocol:
      - "wide_in"
    sbr_port_protocol:
      - "wide_out"
  - name: "hbm6"
    addr_range:
      - start: 0x8060_0000
        end: 0x806F_FFFF
    sbr_port_protocol:
      - "wide_out"
  - name: "hbm7"
    addr_range:
      - start: 0x8070_0000
        end: 0x807F_FFFF
    sbr_port_protocol:
      - "wide_out"
  - name: "hbm8"
    addr_range:
      - start: 0x8080_0000
        end: 0x808F_FFFF
    sbr_port_protocol:
      - "wide_out"
  - name: "hbm9"
    addr_range:
      - start: 0x8090_0000
        end: 0x809F_FFFF
    sbr_port_protocol:
      - "wide_out"
  - name: "hbm10"
    addr_range:
      - start: 0x80A0_0000
        end: 0x80AF_FFFF
    sbr_port_protocol:
      - "wide_out"
  - name: "hbm11"
    addr_range:
      - start: 0x80B0_0000
        end: 0x80BF_FFFF
    sbr_port_protocol:
      - "wide_out"
  - name: "hbm12"
    addr_range:
      - start: 0x80C0_0000
        end: 0x80CF_FFFF
    sbr_port_protocol:
      - "wide_out"
  - name: "hbm13"
    addr_range:
      - start: 0x80D0_0000
        end: 0x80DF_FFFF
    sbr_port_protocol:
      - "wide_out"
  - name: "hbm14"
    addr_range:
      - start: 0x80E0_0000
        end: 0x80EF_FFFF
    sbr_port_protocol:
      - "wide_out"
  - name: "hbm15"
    addr_range:
      - start: 0x80F0_0000
        end: 0x80FF_FFFF
    sbr_port_protocol:
      - "wide_out"

routers:
  - name: "group_router"
    array: [4, 4]
    degree: 5

connections:
  - src: "group"
    dst: "group_router"
    src_range:
    - [0, 3]
    - [0, 3]
    dst_range:
    - [0, 3]
    - [0, 3]
    dst_dir: "Eject"
  # HBM West
  - src: "hbm0"
    dst: "group_router"
    dst_idx: [0, 0]
    dst_dir: "West"
  - src: "hbm1"
    dst: "group_router"
    dst_idx: [0, 1]
    dst_dir: "West"
  - src: "hbm2"
    dst: "group_router"
    dst_idx: [0, 2]
    dst_dir: "West"
  - src: "hbm3"
    dst: "group_router"
    dst_idx: [0, 3]
    dst_dir: "West"
  # HBM North
  - src: "hbm6"
    dst: "group_router"
    dst_idx: [0, 3]
    dst_dir: "North"
  - src: "hbm7"
    dst: "group_router"
    dst_idx: [1, 3]
    dst_dir: "North"
  # HBM North
  - src: "hbm10"
    dst: "group_router"
    dst_idx: [3, 3]
    dst_dir: "North"
  - src: "hbm11"
    dst: "group_router"
    dst_idx: [2, 3]
    dst_dir: "North"
  # HBM East
  - src: "hbm15"
    dst: "group_router"
    dst_idx: [3, 3]
    dst_dir: "East"
  - src: "hbm14"
    dst: "group_router"
    dst_idx: [3, 2]
    dst_dir: "East"
  - src: "hbm13"
    dst: "group_router"
    dst_idx: [3, 1]
    dst_dir: "East"
  - src: "hbm12"
    dst: "group_router"
    dst_idx: [3, 0]
    dst_dir: "East"
  # HBM South
  - src: "hbm9"
    dst: "group_router"
    dst_idx: [3, 0]
    dst_dir: "South"
  - src: "hbm8"
    dst: "group_router"
    dst_idx: [2, 0]
    dst_dir: "South"
  - src: "hbm4"
    dst: "group_router"
    dst_idx: [1, 0]
    dst_dir: "South"
  # Special
  - src: "host_hbm5_peri"
    dst: "group_router"
    dst_idx: [0, 0]
    dst_dir: "South"
