# Copyright 2025 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

# Create group for core $3 from group $1 tile $2 (core_id=NUM_CORES_PER_group*$1+NUM_CORES_PER_TILE*$2+$3)

catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Params /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/BootAddr}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/clk_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/rst_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -radix unsigned /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/hart_id_i}

catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -divider Instructions}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/inst_addr_o}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/inst_data_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/inst_valid_o}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/inst_ready_i}

catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -divider Load/Store}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/data_qaddr_o}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/data_qvalid_o}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/data_qready_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/data_pdata_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/data_pvalid_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/data_pready_o}

catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -divider Accelerator}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/acc_qreq_o}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/acc_qrsp_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/acc_qvalid_o}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/acc_qready_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/acc_prsp_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/acc_pvalid_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/acc_pready_o}

catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/illegal_inst}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/stall}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/lsu_stall}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/acc_stall}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/zero_lsb}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/pc_d}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/pc_q}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/wfi_d}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/wfi_q}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/fcsr_d}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/fcsr_q}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch -divider LSU}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/ls_size}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/ls_amo}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/ld_result}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/lsu_qready}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/lsu_qvalid}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/lsu_pvalid}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/lsu_pready}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/lsu_rd}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/retire_load}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/retire_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/retire_acc}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch -divider ALU}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/opa}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/opb}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/iimm}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/uimm}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/jimm}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/bimm}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/simm}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/adder_result}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/alu_result}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/rd}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/rs1}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/rs2}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/gpr_raddr}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/gpr_rdata}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/gpr_waddr}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/gpr_wdata}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/gpr_we}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/consec_pc}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/sb_d}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/sb_q}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/is_load}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/is_store}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/is_signed}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/ls_misaligned}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/ld_addr_misaligned}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/st_addr_misaligned}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/valid_instr}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/exception}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/alu_op}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/opa_select}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/opb_select}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/write_rd}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/uses_rd}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/next_pc}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/rd_select}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/rd_bypass}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/is_branch}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/csr_rvalue}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/csr_en}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/acc_register_rd}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/operands_ready}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/dst_ready}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/opa_ready}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/opb_ready}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/shift_opa}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/shift_opa_reversed}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/shift_right_result}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/shift_left_result}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/shift_opa_ext}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/shift_right_result_ext}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/shift_left}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/shift_arithmetic}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/alu_opa}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/alu_opb}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/alu_writeback}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/acc_mem_cnt_d}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/acc_mem_cnt_q}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/acc_mem_str_cnt_d}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/acc_mem_str_cnt_q}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/core_events_o}

catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch -group Internal -group RF /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/i_snitch_regfile/*}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Snitch -group Internal /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_snitch/*}

catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/issue_valid_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/issue_ready_o}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/issue_req_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/issue_rsp_o}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/rsp_valid_o}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/rsp_ready_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/rsp_o}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/spatz_mem_req_o}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/spatz_mem_req_valid_o}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/spatz_mem_req_ready_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/spatz_mem_rsp_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/spatz_mem_rsp_valid_i}

catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group "FPU Sequencer" /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/gen_fpu_sequencer/i_fpu_sequencer/*}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group "FPU Sequencer" -group FPR /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/gen_fpu_sequencer/i_fpu_sequencer/i_fpr/*}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group "FPU Sequencer" -group LSU /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/gen_fpu_sequencer/i_fpu_sequencer/i_fp_lsu/*}

catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group Controller /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/i_controller/*}

catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group VRF -divider RegisterWrite}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group VRF /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/i_vrf/waddr_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group VRF /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/i_vrf/wdata_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group VRF /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/i_vrf/we_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group VRF /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/i_vrf/wbe_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group VRF /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/i_vrf/wvalid_o}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group VRF -divider RegisterRead}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group VRF /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/i_vrf/raddr_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group VRF /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/i_vrf/rdata_o}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group VRF /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/i_vrf/re_i}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group VRF /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/i_vrf/rvalid_o}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group VRF -divider Internal}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group VRF /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/i_vrf/waddr}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group VRF /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/i_vrf/wdata}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group VRF /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/i_vrf/we}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group VRF /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/i_vrf/wbe}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group VRF /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/i_vrf/raddr}
catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group VRF /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/i_vrf/rdata}

catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group VLSU /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/i_vlsu/*}

catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group VSLDU /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/i_vsldu/*}

catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Spatz -group VFU /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/i_spatz/i_vfu/*}

catch {add wave -noupdate -group core\[$1\]\[$2\]\[$3\] -group Internal /mempool_tb/dut/i_mempool_cluster/gen_groups_x\[[expr  ${1}/${4}]\]/gen_groups_y\[[expr  ${1}%${4}]\]/gen_rtl_group/i_group/i_mempool_group/gen_tiles\[$2\]/i_tile/gen_cores\[$3\]/gen_mempool_cc/riscv_core/*}
