#!/usr/bin/env python3
"""Compare the RH-livelock arms at serve_timeout/hold_window 2047 vs 4095.

The 4095 arms need a WIDER build: MshrCfgHoldCntMax/W were 2047/11, and the CSR write path
refuses anything above the max (mempool_group_mshr_cfg.sv cnt_ok), so a 4095 write against an
11-bit image kept the reset default and set the sticky RANGE bit -- an arm that looks configured
and is not. Widened to 4095/12; images build_{vcs,q}_8x8_w4.

Reads hardware/s8_<arm>/transcript (2047) and hardware/s8w4_<arm>/transcript (4095) directly
rather than results.tsv, because the 4095 arms are a separate campaign with their own prefix.
"""
import os, re, sys

ROOT = "/usr/scratch/fenga1/zexifu/TeraNoC_Spatz/TeraNoC"
OUT  = os.path.join(ROOT, "docs/benchmarks/8x8_scaleup/w4095_vs_2047.md")
ARMS = "/tmp/claude-620771/affected.txt"
PEAK = {"fp16": 8192, "fp32": 4096}          # MAC/cycle at 8x8


def scrape(path):
    if not os.path.exists(path):
        return None
    raw = open(path, "rb").read()
    txt = b"\n".join(l[2:] if l.startswith(b"# ") else l for l in raw.split(b"\n"))
    d = {"rh": txt.count(b"RH STUCK"), "range_err": txt.count(b"RANGE")}
    cyc = re.findall(rb"execution took (\d+)", txt)
    d["cycles"] = int(cyc[-1]) if cyc else None
    u = re.search(rb"\[FPU FINAL\][^\n]*?util=([0-9.]+)%", txt)
    if u:
        d["util"], d["recon"] = float(u.group(1)), False
    else:
        num = den = 0
        for m in re.finditer(rb"\[FPUG\]\s+(\S+)\s+cyc=\d+\s+denom=(\d+)\s+busy=\s*([0-9, ]+)", txt):
            if m.group(1) != b"bench":
                continue
            v = [int(x) for x in m.group(3).split(b",") if x.strip()]
            num += sum(v); den += int(m.group(2)) * len(v)
        d["util"] = (100.0 * num / den) if den else None
        d["recon"] = True
    last = re.findall(rb"\[FPU\] bench cyc=(\d+)", txt)
    d["last_cyc"] = int(last[-1]) if last else None
    # Confirm the CSR actually took: the probe prints subs=<n>/<target>.
    t = re.search(rb"subs=\d+/(\d+)", txt)
    d["target"] = int(t.group(1)) if t else None
    return d


def eff(arm, cycles):
    """ideal/actual -- the metric to RANK on; the TB util counter is lane occupancy."""
    pr, sh = arm.split("_", 1)
    M, N, P = (int(x) for x in sh.split("x"))
    return 100.0 * (M * N * P / PEAK[pr]) / cycles if cycles else None


def fmt(v, suf="", nd=2):
    return "-" if v is None else ("%.*f%s" % (nd, v, suf) if isinstance(v, float) else "%s%s" % (v, suf))


def main():
    arms = [a.strip() for a in open(ARMS) if a.strip()]
    rows, done = [], 0
    for arm in arms:
        b = scrape(os.path.join(ROOT, "hardware", "s8_" + arm, "transcript"))
        n = scrape(os.path.join(ROOT, "hardware", "s8w4_" + arm, "transcript"))
        if n is None:
            rows.append((arm, b, None, None)); continue
        done += 1
        rows.append((arm, b, n, None))
    lines = [
        "# serve_timeout / hold_window 2047 vs 4095 — the RH-livelock arms",
        "",
        "Generated by `scripts/gen_w4095_comparison.py`. **Re-run rather than trusting a stale copy.**",
        "",
        "`4095` arms run image `build_{vcs,q}_8x8_w4` (`MshrCfgHoldCntMax/W` 2047/11 → **4095/12**);",
        "`2047` arms are the main campaign's `build_{vcs,q}_8x8`. ELF define sets verified identical",
        "apart from the two CSR constants; the baseline recipe reproduces the shipped ELF byte-for-byte",
        "(`group_mshr_merge_reqs=16`, `EXTRA_DEFINES=-DMATMUL_SPOTCHECK=1` — both easy to miss).",
        "",
        "`target` is the cohort size the probe reports (`subs=n/target`) — it must match between the",
        "two columns, or the comparison is not matched. `eff` is `ideal/actual`; rank on it, not on the",
        "TB `util` counter, which is lane occupancy.",
        "",
        "A livelocked arm never prints `execution took`, so most 2047 rows have **no cycle count at",
        "all** — they were killed by the wall clock. Reporting a blank there would read as missing",
        "data; the outcome column says `livelock >N` with the last traced cycle, which is a FLOOR,",
        "not a completion. Only a `done` row can be compared cycle-to-cycle.",
        "",
        "| arm | target | outcome 2047 | outcome 4095 | util 2047 | util 4095 | RH 2047 | RH 4095 |",
        "|---|---:|---|---|---:|---:|---:|---:|",
    ]
    def outcome(d):
        if d is None:
            return "_not run_"
        if d.get("cycles"):
            return "**done %d** (eff %.2f%%)" % (d["cycles"], eff(arm, d["cycles"]) or 0)
        if d.get("last_cyc"):
            return "livelock >%d" % d["last_cyc"]
        return "_no trace_"

    for arm, b, n, _ in rows:
        warn = " ⚠︎RANGE" if (n and n.get("range_err")) else ""
        tgt = (n or b or {}).get("target")
        # A target mismatch between the two columns means the arms are NOT matched -- say so loudly
        # rather than printing a comparison that looks valid.
        if b and n and b.get("target") and n.get("target") and b["target"] != n["target"]:
            warn += " ⚠︎TARGET %s vs %s" % (b["target"], n["target"])
        lines.append("| `%s` | %s%s | %s | %s | %s | %s | %s | %s |"
                     % (arm, fmt(tgt), warn, outcome(b), outcome(n) if n else "_pending_",
                        fmt(b and b.get("util"), "%"), fmt(n and n.get("util"), "%"),
                        fmt(b and b.get("rh")), fmt(n and n.get("rh"))))
    lines += ["", "%d of %d 4095 arms have delivered." % (done, len(arms)), ""]
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s (%d/%d delivered)" % (OUT, done, len(arms)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
