#!/bin/bash
# Create a per-shape DECODE-GEMM app and build its ELF to a private path.
#   usage: gen_decode_shape_app.sh B D I [16|32]
#
# Decode shape: C[B][I] = A[B][D] x W[D][I], mapped to GEMM as M=B, N=D, P=I. No transpose is
# required -- A[b][d] is contiguous for the scalar load and W[d][p:p+VL] is contiguous for the
# vector load -- so the inner loop is the prefill kernel's; only the WORK SPLIT differs (the
# P dimension is split as well as M, or a batch of 32 leaves a 1024-core mesh ~98% idle).
#
# ONE SOURCE, like gen_gemm_shape_app.sh. The app is a COPY of sp-decode-gemm-fp16; only
# data_gemm.h and the shape in matmul.json differ. The first version of this benchmark shipped
# four hand-written app dirs whose main.c were BYTE-IDENTICAL -- which means a kernel fix has to
# be made four times, and the copy that gets missed silently measures different code on the
# fleet. Never hand-copy an app to change its shape.
set -u
B=$1; D=$2; I=$3; PREC=${4:-16}; S="${B}x${D}x${I}"
ROOT=/usr/scratch/fenga1/zexifu/TeraNoC_Spatz/TeraNoC
APPS=$ROOT/software/apps/spatz_apps
SRC=$APPS/sp-decode-gemm-fp16
PFX=sp-decode
d=$APPS/$PFX-$S

[ -d "$SRC" ] || { echo "MISSING SOURCE $SRC"; exit 1; }
rm -rf "$d"; mkdir -p "$d/script" "$d/data"
cp "$SRC/main.c" "$d/main.c"
cp -r "$SRC/kernel" "$d/kernel" 2>/dev/null
cp "$SRC/script/gen_data.py" "$d/script/gen_data.py"
cp "$SRC/data/layer.h" "$d/data/layer.h" 2>/dev/null
cat > "$d/script/matmul.json" <<JSON
// DECODE-shape GEMM: C[B][I] = A[B][D] x W[D][I].
// B=${B} (batch), D=${D} (residual/hidden), I=${I} (output).
// Mapped to GEMM as M=B, N=D, P=I. Generated by scripts/gen_decode_shape_app.sh -- do not
// hand-edit, and do not copy this directory to make another shape.
{
    kernel: "GEMM"
    M: ${B},
    N: ${D},
    P: ${I},
    alpha: 0,
    transpose_A: false,
    transpose_B: false,
    prec: ${PREC},
    expand: 0
}
JSON

# The app target depends on main.c.o, not on the define set: if the binary is newer than the
# source, make does NOTHING and reports success (runtime.mk:165). Always clear it first.
rm -f "$d"/*.o "$d"/kernel/*.o "$ROOT/software/bin/apps/spatz_apps/$PFX-$S" 2>/dev/null

LOG=/tmp/claude-620771/decodebuild_${OUT_PREFIX:-}$S.log
if (cd "$APPS" && timeout 3600 make "$PFX-$S" \
      config=${CONFIG:-terapool_spatz4_fpu} \
      group_mshr_merge_reqs=${MERGE_REQS:-16} \
      ${MAKE_VARS:-} EXTRA_DEFINES="${EXTRA_DEFINES:-}" >"$LOG" 2>&1) \
   && [ -s "$ROOT/software/bin/apps/spatz_apps/$PFX-$S" ]; then
  OUT="$ROOT/hardware/${OUT_PREFIX:-dec_}${S}.elf"
  cp -f "$ROOT/software/bin/apps/spatz_apps/$PFX-$S" "$OUT"
  echo "ELF_OK $S -> $(basename "$OUT") ($(stat -c%s "$OUT") bytes)"
else
  echo "BUILD_FAIL $S"; tail -5 "$LOG"; exit 1
fi
